### ISSUE TITLE
mixed content error

### ISSUE THREAD

**Issue by thikade** [sdaschner/kaffeehaus-demo#3]
Trotz der letzten Änderung habe ich den mixed-content error immer noch:
- `form.js:18 Mixed Content: The page at 'https://kaffeehaus-ama.apps.ocp00.cloud.2i.at/order.html' was loaded over HTTPS, but requested an insecure resource 'http://kaffeehaus-ama.apps.ocp00.cloud.2i.at/types/espresso/origins'. This request has been blocked; the content must be served over HTTPS.`

Der Fehler passiert beim 2. Fetch `fetch(url)` in forms.js:18.  
mein /types Json enthält nämlich URLs mit scheme `http`, **obwohl** /types mit **https** geholt wird ! Wie/wo werden die Types-Links generiert?

- GET https://kaffeehaus-ama.apps.ocp00.cloud.2i.at/types
```
[{"type":"Espresso","_links":{"origins":"http://kaffeehaus-ama.apps.ocp00.cloud.2i.at/types/espresso/origins"}},{"type":"Filter","_links":{"origins":"http://kaffeehaus-ama.apps.ocp00.cloud.2i.at/types/filter/origins"}},{"type":"Melange","_links":{"origins":"http://kaffeehaus-ama.apps.ocp00.cloud.2i.at/types/melange/origins"}}]
```

**Comment by sdaschner** [comment]
Mit 0fa80d9 gefixed
